---
- name: Install common packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ common_packages }}"


- name: Remove all files in /usr/share/nginx/html
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /usr/share/nginx/html/*

- name: Clone portfolio repository
  ansible.builtin.git:
    repo: 'https://github.com/UjjwalBudha/portfolio.git'
    dest: '/tmp/portfolio'
    force: yes

- name: Copy portfolio contents to /usr/share/nginx/html
  ansible.builtin.copy:
    src: /tmp/portfolio/
    dest: /usr/share/nginx/html/
    remote_src: yes
  notify: Restart nginx