---
- name: Install common packages using yum
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - python3-pip
    - python3-boto3
    - nginx

- name: Install botocore
  ansible.builtin.pip: 
    name: "{{ item }}"
    state: present
  loop:
    - botocore
    - s3transfer
    - packaging

- name: Remove all files in /usr/share/nginx/html
  ansible.builtin.file:
    path: "{{ web_dir }}"
    state: absent
  with_fileglob:
    - '*'
  notify: Restart nginx

# - name: Download file from s3 to ec2
#   amazon.aws.s3_object:
#     bucket: "test-intern-github-action"
#     dest: "{{ destination }}"
#     object: "{{ object }}"
#     mode: get
#     overwrite: true
#   notify: Restart nginx
