---
- name: Install common packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ common_packages }}"


- name: Remove all files in /usr/share/nginx/html
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "{{ website_dir }}"

- name: Clone portfolio repository
  ansible.builtin.git:
    repo: "{{ github_repo }}"
    dest: "{{ web_dir_tmp }}"
    force: yes

- name: Copy portfolio contents to /usr/share/nginx/html
  ansible.builtin.copy:
    src: "{{ web_dir_tmp }}"
    dest: "{{ destination }}"
    remote_src: yes
  notify: Restart nginx