name: github_action_to_ec2
on:
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli


      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform destroy
        run: |
          cd terraform
          terraform destroy -var-file=dev.tfvars -auto-approve